# Generated by Django 2.1.2 on 2018-10-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('collection', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
                ('owned', models.BooleanField(default=False)),
                ('image', models.ImageField(default='magicdb/card_images/no-img.jpg', upload_to='magicdb/card_images')),
            ],
        ),
    ]
