# Generated by Django 2.1.2 on 2018-10-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
