# Generated by Django 2.1.2 on 2018-11-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicdb', '0003_card_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='users',
            new_name='owned_by',
        ),
    ]
